### ISSUE TITLE
Shiny App Cleanup Tasks

### ISSUE THREAD

**Issue by dblodgett-usgs** [USGS-R/wateRuse#75] opened 2016-05-10 20:23 UTC
@ldecicco-USGS, @cadieter-usgs,  and @mamaupin-usgs will enumerate and pass off to others.

@rwdudley-usgs will lead, @jshourds-usgs will review.

**Comment by cadieter-usgs** [comment] 2016-05-11 15:39
Add the function to allow the mouse hover to get the area name (i.e. county)  and data element value on the choropleth maps.  Let me know if you want me to move this to a different issue.

**Comment by ldecicco-USGS** [comment] 2016-05-12 14:14
I did add a hover to the map. It's not super great, but it seems to work most of the time.

**Comment by ldecicco-USGS** [comment] 2016-05-12 14:16
@rwdudley-usgs and @jshourds-usgs  and @cadieter-usgs and @mamaupin-usgs 
Why don't you guys start by using this GitHub issues to log the bugs that appear in the latest version of the shiny app. Don't add requested new features (you can create new issues for that). When we have a few issues, I'll try to help @rwdudley-usgs walk through the first batch of troubleshooting. Then he should be able to go from there.

**Comment by rwdudley-usgs** [comment] 2016-05-18 15:14
Hi @ldecicco-USGS I'm back from vacation. I'm probably missing some items but right now I identify the following Shiny-related tasks:
- [x] Add buttons for exporting png and pdf formats for all plots
- [ ] Review and hook up @grrmartin-USGS 's stacked bar function to Shiny
- [ ] Troubleshooting bugs as they arise - though it appears none have been posted here yet

Others? I have yet to review the Shiny code; I may need a tutorial...

**Comment by ldecicco-USGS** [comment] 2016-05-18 21:28
I'd start by playing around with the app itself (not necessarily try to dig into the code immediately). Like, if you have different water use data sets, try those all out. When we do find a few issues, we can get a web ex set up to sort out what all is going on....

**Comment by rwdudley-usgs** [comment] 2016-05-19 14:01
Will do.

**Comment by ldecicco-USGS** [comment] 2016-05-20 19:07
I restructured the app a bit. Now, each tab has it's own file. @rwdudley-usgs , I think you could copy the file "inst/plotMultiElem.R", and try to make a new one for the new box plot function. Then on the ui.R file, you'll need to add a new tab. Copy the multiElement tab here:

https://github.com/USGS-R/wateRuse/blob/master/inst/shiny/ui.R#L59

So copy this part:

```
     tabPanel(title = tagList("Multi-Elements",shiny::icon("bar-chart")),
              value = "multiElem",
              fluidRow(
                column(9, 
                       plotOutput("plotMultiElem",width = 500, height = 500))

              ),
              h4(""),
              fluidRow(
                column(3, downloadButton('downloadPlotmultiElem', 'Download PNG')),
                column(3, downloadButton('downloadPlotmultiElemPDF', 'Download PDF')),
                column(3, downloadButton('downloadPlotmultiElemData', 'Download Data'))
              ),
              h4("R Code:"),
              verbatimTextOutput("plotMultiElemCode")
     ),
```

Change all the id's to something about boxplots.  Give it a little try, and if you get confused, let me know.

**Comment by rwdudley-usgs** [comment] 2016-05-20 19:24
Ok, I'll give it a go! 
I've been doing some testing and have discovered some Shiny bugs/features I'll post in a bit.

**Comment by ldecicco-USGS** [comment] 2016-05-20 19:25
Sounds good. Make sure to pull from upstream first!

**Comment by rwdudley-usgs** [comment] 2016-05-20 20:15
Shiny bugs (or features) for the first three functions (testing in Chrome browser). I have yet to methodically test the other functions. 
The first couple items common to all three I checked might not be considered bugs - common theme is lack of persistence of selections that users might expect. For example, for the first item below, one might choose PS.SWPop for one state, then switching to look at another state, the data.element changes to PS.GWPop instead of remaining PS.SWPop.
- For all three: 
1. value of `data.elements` in Compare Two Years (or `data.elements.x.y[1]` in Compare Two Elements or `data.elements[1]` in Multi-Elements) changes when (de)selecting _Choose States_; seems to revert to first of its element type
2.  `areas` selected in _Choose Areas_ change when switching between STATECOUNTYCODE and COUNTYNAME or when (de)selecting _Choose States_ 
3. not a bug, but output files for Compare Two Years should be named _plotTwoYears_ to be consistent with _plotTwoElement_
4. Compare Two Elements: for `data.elements.x.y[2]`, user can't select any other element other than the first in the list; immediately reverts upon selection 
5. Multi-Elements: for `data.elements[2]`, user can't select any other element other than the first in the list; immediately reverts upon selection

**Comment by ldecicco-USGS** [comment] 2016-05-20 20:21
I edited your comment so I could respond...

**Comment by ldecicco-USGS** [comment] 2016-05-20 20:29
1. Yes, when changing the State or the actual data file, everything resets. This was done to check that everything in all the dropdowns actually correlates to some data. So a user can't pick something that doesn't exist
2. Yes, it's much, much easier this way from a coding standpoint.  It might be possible to create a key and retain what was in the previous state (I don't think you can count on the same orders....but may you can). Also, a lot of data sets only have the option "Area"...so I don't think it's much of an issue?
3. That can be done
4. You have to pick a different Data Element Type first (?...I think that's what you are describing). It sounded like people wanted the "type" filtered to make picking the specific elements a more manageable list.  If that's not what you are talking about, let me know...it works to me at least.
5. Same as above.

**Comment by ldecicco-USGS** [comment] 2016-05-20 20:34
Ha, nevermind! I do now see 4 and 5...I think I can fix that pretty quick.

**Comment by ldecicco-USGS** [comment] 2016-05-20 21:32
3, 4, and 5 should be OK now.
1 and 2 in my opinion are not worth the effort, but if it's a big deal...we can work on it.

**Comment by rwdudley-usgs** [comment] 2016-05-23 11:23
Great! Thanks. 
I also think 1 and 2 are not a big deal.

**Comment by grrmartin-USGS** [comment] 2016-05-25 00:39
In the Multi-Elements graph, when you pick the second Data Element Type y/Data Element y, it only wants to use the first entry on the Data Element y: pick list: (No mater what you pick, it reverts to the first item on the list.)  This seems to be the same issue as number 4 above.

![multielementissuecapture](https://cloud.githubusercontent.com/assets/18426661/15524337/95bb6de8-21ef-11e6-8d8e-b0f86c93cde2.JPG)

**Comment by grrmartin-USGS** [comment] 2016-05-25 01:02
Unable to deselect areas (graph remains same).  Choose Areas/Click Here to Select Areas/Deselect All/

![deselectareaissuecapture](https://cloud.githubusercontent.com/assets/18426661/15524718/d04bf1aa-21f2-11e6-9862-b7f669276a96.JPG)

**Comment by ldecicco-USGS** [comment] 2016-05-25 14:25
The Select All and Deselect All won't work until you then click the "Click Here to Switch Areas". This is because when I had it doing it on the fly for bigger data sets (lots of "areas" be it counties, aquifers, HUCs), the app would go a little crazy trying to switch areas too fast (if the user clicked the buttons too fast, the previous calculations were still going on, then the code would get all confused and freeze up).

**Comment by ldecicco-USGS** [comment] 2016-05-25 14:26
@grrmartin-USGS I think if you do another pull from upstream, the select issue you mentioned is fixed:

```
git pull upstream master
```

**Comment by jshourds-usgs** [comment] 2016-05-25 16:15
So this is pretty picky but when uploading the regional dump file and playing around in shiny, is there any way we can list states in alphabetical order?  I think selecting state would be easier that way.  No offense to Wisc which shows up first... ;-)  I checked the indiv dump files and they are listed in alphabetical order so I'm not sure how this comes about.   Thanks!

**Comment by jshourds-usgs** [comment] 2016-05-25 16:18
Sort of the same as above, when choosing the years to plot they should be in order, either newest to oldest or oldest to newest available.  We may not be at this nitpicky stage yet so this can serve as a placeholder.

**Comment by ldecicco-USGS** [comment] 2016-05-25 16:52
I just merged a pull request that I think should order the states and years a bit better (or worse, if you like WI on top...)

**Comment by jshourds-usgs** [comment] 2016-05-25 17:39
Yay-- looks fabulous!  Thank you @ldecicco-USGS ! And not to worry, WV and WY are the very bottom of the barrel!

**Comment by ldecicco-USGS** [comment] 2016-05-27 16:36
I'm going to close this Issue. If new bugs come up, make a new Issue for the specific bugs, and assign to @rwdudley-usgs

**Closed as completed by ldecicco-USGS** 2016-05-27 16:36 UTC
Labels: enhancement
