### ISSUE TITLE
Plots not rendering properly

### ISSUE THREAD

**Issue by grrmartin-USGS** [USGS-R/wateRuse#196] opened 2017-06-26 05:46 UTC
Plots have become flattened. No R changes made however many PC system updates recently.  Getting warnings on widgets and  'We recommend that you use the dev version of ggplot2 with `ggplotly()`'  however this will not install as dependency package 'tibble' not available for 'ggplot2'

![wateruseplotsflatcapture](https://user-images.githubusercontent.com/18426661/27526063-153497f2-5a11-11e7-8807-8328933b371f.JPG)

[Rerrors.docx](https://github.com/USGS-R/wateRuse/files/1101119/Rerrors.docx)

**Comment by ldecicco-USGS** [comment] 2017-06-26 19:26
I made some edits here on the #197 pull request. There might be other/better ways to deal with size, that's just the first thing I came up with. @rwdudley-usgs or @grrmartin-USGS  want to have a look?

**Comment by rwdudley-usgs** [comment] 2017-06-27 13:28
Tried it this morning before doing a pull and worked fine. Did a pull update and now I can't load the excel data files I had just tested. I get `ERROR: VECTOR_ELT() can only be applied to a 'list', not a 'NULL'`

**Comment by ldecicco-USGS** [comment] 2017-06-27 17:53
Have you updated your packages recently? The changes in the PR don't affect anything to do with opening the Excel files for me, and I tend to update my packages daily.

**Comment by grrmartin-USGS** [comment] 2017-06-30 19:01
Plots rendered after pulling master and updating packages.  Plot sizes now about half width and height as originally.
![updatedplotcapture](https://user-images.githubusercontent.com/18426661/27750212-d6144aa8-5da4-11e7-9754-dd3f2595db77.JPG)
![originalplotcapture](https://user-images.githubusercontent.com/18426661/27750219-dc8257c2-5da4-11e7-8004-d55b62ec8343.JPG)

**Comment by grrmartin-USGS** [comment] 2017-06-30 19:04
Actually now about 1/3 width and 1/2 height originally.

**Comment by emmurray-usgs** [comment] 2017-07-13 21:06
I have this same issue with plots being about 1/2 width & height. When they export they stay this size so all of the data points are squished at the bottom & indistinguishable from each other. Is there a way to re-size the plots in the program besides zooming?

**Comment by dblodgett-usgs** [comment] 2017-08-03 02:00
I just got Laura's latest in #197 loaded up and am looking at some sample data... Plot sizes look good. Should we merge that PR and get others to test?

**Comment by grrmartin-USGS** [comment] 2017-08-03 02:27
Sure

**Comment by dblodgett-usgs** [comment] 2017-08-10 13:45
This is a duplicate of #200 going to close.

**Closed as completed by dblodgett-usgs** 2017-08-10 13:45 UTC
